language: android
android:
  components:
    - android-24
    - build-tools-24.0.3
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew assemble test check